# Generated by Django 4.2.23 on 2025-07-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='price_range',
            field=models.CharField(choices=[('~999円', '〜999円'), ('1000-1999円', '1,000〜1,999円'), ('2000-2999円', '2,000〜2,999円'), ('3000-3999円', '3,000〜3,999円'), ('4000-4999円', '4,000〜4,999円'), ('5000円〜', '5,000円〜')], default='1000-1999円', max_length=20),
        ),
    ]
