# Generated by Django 4.2.23 on 2025-07-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_restaurant_price_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='price_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='価格帯下限'),
        ),
    ]
